Update typescript-eslint monorepo to v8.59.2
| datasource | package                          | from   | to     |
| ---------- | -------------------------------- | ------ | ------ |
| npm        | @typescript-eslint/eslint-plugin | 8.56.0 | 8.59.2 |
| npm        | @typescript-eslint/parser        | 8.56.0 | 8.59.2 |


## [v8.59.2](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#8592-2026-05-04)

##### 🩹 Fixes

- **eslint-plugin:** \[no-deprecated] object destructuring values should be treated as declarations ([#12292](https://github.com/typescript-eslint/typescript-eslint/pull/12292))
- **eslint-plugin:** \[no-unsafe-type-assertion] handle crash on recursive template literal types ([#12150](https://github.com/typescript-eslint/typescript-eslint/pull/12150))

##### ❤️ Thank You

- Dima Barabash
- Kirk Waiblinger [@kirkwaiblinger](https://github.com/kirkwaiblinger)

See [GitHub Releases](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.59.2) for more information.

You can read about our [versioning strategy](https://typescript-eslint.io/users/versioning) and [releases](https://typescript-eslint.io/users/releases) on our website.


## [v8.59.1](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#8591-2026-04-27)

##### 🩹 Fixes

- **eslint-plugin:** \[no-unnecessary-condition] treat void as nullish in no-unnecessary-condition ([#12241](https://github.com/typescript-eslint/typescript-eslint/pull/12241))
- **eslint-plugin:** \[no-unnecessary-type-arguments] handle instantiation expressions ([#12220](https://github.com/typescript-eslint/typescript-eslint/pull/12220))
- **eslint-plugin:** \[no-unnecessary-type-assertion] avoid false positive in logical assignment assertions ([#12278](https://github.com/typescript-eslint/typescript-eslint/pull/12278))
- **eslint-plugin:** \[no-unnecessary-type-assertion] preserve phantom type arguments in generic inference ([#12269](https://github.com/typescript-eslint/typescript-eslint/pull/12269))
- **eslint-plugin:** \[no-unnecessary-type-assertion] preserve index signatures in undefined unions ([#12257](https://github.com/typescript-eslint/typescript-eslint/pull/12257))
- **eslint-plugin:** \[no-unnecessary-type-assertion] fix crash "TypeError: checker.getTypeArguments is not a function" ([#12246](https://github.com/typescript-eslint/typescript-eslint/pull/12246))

##### ❤️ Thank You

- anasm266 [@anasm266](https://github.com/anasm266)
- Anshika Jain [@Anshikakalpana](https://github.com/Anshikakalpana)
- Ulrich Stark
- yugo innami [@nami8824](https://github.com/nami8824)

See [GitHub Releases](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.59.1) for more information.

You can read about our [versioning strategy](https://typescript-eslint.io/users/versioning) and [releases](https://typescript-eslint.io/users/releases) on our website.


## [v8.59.0](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#8590-2026-04-20)

##### 🚀 Features

- **eslint-plugin:** \[no-unnecessary-type-assertion] report more cases based on assignability ([#11789](https://github.com/typescript-eslint/typescript-eslint/pull/11789))

##### ❤️ Thank You

- Ulrich Stark

See [GitHub Releases](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.59.0) for more information.

You can read about our [versioning strategy](https://typescript-eslint.io/users/versioning) and [releases](https://typescript-eslint.io/users/releases) on our website.


## [v8.58.2](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#8582-2026-04-13)

##### 🩹 Fixes

- **eslint-plugin:** \[no-unnecessary-condition] use assignability checks in checkTypePredicates ([#12147](https://github.com/typescript-eslint/typescript-eslint/pull/12147))
- remove tsbuildinfo cache file from published packages ([#12187](https://github.com/typescript-eslint/typescript-eslint/pull/12187))

##### ❤️ Thank You

- Abhijeet Singh [@cseas](https://github.com/cseas)
- 송재욱

See [GitHub Releases](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.58.2) for more information.

You can read about our [versioning strategy](https://typescript-eslint.io/users/versioning) and [releases](https://typescript-eslint.io/users/releases) on our website.


## [v8.58.1](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#8581-2026-04-08)

##### 🩹 Fixes

- **eslint-plugin:** \[no-unused-vars] fix false negative for type predicate parameter ([#12004](https://github.com/typescript-eslint/typescript-eslint/pull/12004))

##### ❤️ Thank You

- MinJae [@Ju-MINJAE](https://github.com/Ju-MINJAE)

See [GitHub Releases](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.58.1) for more information.

You can read about our [versioning strategy](https://typescript-eslint.io/users/versioning) and [releases](https://typescript-eslint.io/users/releases) on our website.


## [v8.58.0](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#8580-2026-03-30)

##### 🚀 Features

- support TypeScript 6 ([#12124](https://github.com/typescript-eslint/typescript-eslint/pull/12124))

##### 🩹 Fixes

- **eslint-plugin:** \[prefer-regexp-exec] avoid fixing unknown RegExp flags ([#12161](https://github.com/typescript-eslint/typescript-eslint/pull/12161))
- **eslint-plugin:** \[no-extraneous-class] handle index signatures ([#12142](https://github.com/typescript-eslint/typescript-eslint/pull/12142))
- **eslint-plugin:** crash in `no-unnecessary-type-arguments` ([#12163](https://github.com/typescript-eslint/typescript-eslint/pull/12163))

##### ❤️ Thank You

- ej shafran [@ej-shafran](https://github.com/ej-shafran)
- Evyatar Daud [@StyleShit](https://github.com/StyleShit)
- GG ZIBLAKING
- milkboy2564 [@SeolJaeHyeok](https://github.com/SeolJaeHyeok)
- teee32 [@teee32](https://github.com/teee32)

See [GitHub Releases](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.58.0) for more information.

You can read about our [versioning strategy](https://typescript-eslint.io/users/versioning) and [releases](https://typescript-eslint.io/users/releases) on our website.


## [v8.57.2](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#8572-2026-03-23)

##### 🩹 Fixes

- **eslint-plugin:** \[prefer-readonly-parameter-types] preserve type alias infomation ([#11954](https://github.com/typescript-eslint/typescript-eslint/pull/11954))
- **eslint-plugin:** \[no-useless-default-assignment] skip reporting false positives for unresolved type parameters ([#12127](https://github.com/typescript-eslint/typescript-eslint/pull/12127))
- **eslint-plugin:** \[no-unsafe-return] false positive on unwrapping generic ([#12125](https://github.com/typescript-eslint/typescript-eslint/pull/12125))
- **eslint-plugin:** \[no-restricted-types] flag banned generics in extends or implements ([#12120](https://github.com/typescript-eslint/typescript-eslint/pull/12120))
- **eslint-plugin:** \[array-type] ignore Array and ReadonlyArray without type arguments ([#11971](https://github.com/typescript-eslint/typescript-eslint/pull/11971))
- **eslint-plugin:** \[prefer-optional-chain] remove dangling closing parenthesis ([#11865](https://github.com/typescript-eslint/typescript-eslint/pull/11865))

##### ❤️ Thank You

- Kirk Waiblinger [@kirkwaiblinger](https://github.com/kirkwaiblinger)
- Konv Suu
- mdm317
- Newton Yuan [@NewtonYuan](https://github.com/NewtonYuan)
- SungHyun627 [@SungHyun627](https://github.com/SungHyun627)
- Tamashoo [@Tamashoo](https://github.com/Tamashoo)

See [GitHub Releases](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.57.2) for more information.

You can read about our [versioning strategy](https://typescript-eslint.io/users/versioning) and [releases](https://typescript-eslint.io/users/releases) on our website.


## [v8.57.1](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#8571-2026-03-16)

##### 🩹 Fixes

- **eslint-plugin:** \[prefer-optional-chain] no report for property on intersection type ([#12126](https://github.com/typescript-eslint/typescript-eslint/pull/12126))

##### ❤️ Thank You

- Newton Yuan [@NewtonYuan](https://github.com/NewtonYuan)

See [GitHub Releases](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.57.1) for more information.

You can read about our [versioning strategy](https://typescript-eslint.io/users/versioning) and [releases](https://typescript-eslint.io/users/releases) on our website.


## [v8.57.0](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#8570-2026-03-09)

##### 🚀 Features

- **eslint-plugin:** \[no-unnecessary-condition] allow literal loop conditions in for/do loops ([#12080](https://github.com/typescript-eslint/typescript-eslint/pull/12080))

##### 🩹 Fixes

- **eslint-plugin:** \[no-base-to-string] fix false positive for toString with overloads ([#12089](https://github.com/typescript-eslint/typescript-eslint/pull/12089))
- **eslint-plugin:** \[prefer-promise-reject-errors] add allow `TypeOrValueSpecifier` to prefer-promise-reject-errors ([#12094](https://github.com/typescript-eslint/typescript-eslint/pull/12094))
- **typescript-estree:** if the template literal is tagged and the text has an invalid escape, `cooked` will be `null` ([#11355](https://github.com/typescript-eslint/typescript-eslint/pull/11355))
- **eslint-plugin:** guard against negative paramIndex in no-useless-default-assignment ([#12077](https://github.com/typescript-eslint/typescript-eslint/pull/12077))
- **eslint-plugin:** handle statically analyzable computed keys in prefer-readonly ([#12079](https://github.com/typescript-eslint/typescript-eslint/pull/12079))
- **eslint-plugin:** \[strict-void-return] false positives with overloads ([#12055](https://github.com/typescript-eslint/typescript-eslint/pull/12055))

##### ❤️ Thank You

- Brad Zacher [@bradzacher](https://github.com/bradzacher)
- Brian Schlenker [@bschlenk](https://github.com/bschlenk)
- Evyatar Daud [@StyleShit](https://github.com/StyleShit)
- James Henry [@JamesHenry](https://github.com/JamesHenry)
- Josh Goldberg
- Kirk Waiblinger [@kirkwaiblinger](https://github.com/kirkwaiblinger)
- Moses Odutusin [@thebolarin](https://github.com/thebolarin)
- Newton Yuan [@NewtonYuan](https://github.com/NewtonYuan)
- SungHyun627 [@SungHyun627](https://github.com/SungHyun627)
- Younsang Na [@nayounsang](https://github.com/nayounsang)

See [GitHub Releases](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.57.0) for more information.

You can read about our [versioning strategy](https://typescript-eslint.io/users/versioning) and [releases](https://typescript-eslint.io/users/releases) on our website.


## [v8.56.1](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#8561-2026-02-23)

This was a version bump only for eslint-plugin to align it with other projects, there were no code changes.

See [GitHub Releases](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.56.1) for more information.

You can read about our [versioning strategy](https://typescript-eslint.io/users/versioning) and [releases](https://typescript-eslint.io/users/releases) on our website.