Update dependency stylelint to v16.14.0
| datasource | package   | from    | to      |
| ---------- | --------- | ------- | ------- |
| npm        | stylelint | 16.13.0 | 16.14.0 |


## [v16.14.0](https://github.com/stylelint/stylelint/blob/HEAD/CHANGELOG.md#16140---2025-01-25)

It fixes 8 bugs and adds features to our `Warning` type.

-   Added: replaced text and corresponding range to `Warning` type ([#8234](https://github.com/stylelint/stylelint/pull/8234)) ([@romainmenke](https://github.com/romainmenke)).
-   Fixed: `SyntaxError: The requested module 'table'...` ([#8325](https://github.com/stylelint/stylelint/pull/8325)) ([@denisx](https://github.com/denisx)).
-   Fixed: `RuleContext['fix']` type ([#8309](https://github.com/stylelint/stylelint/pull/8309)) ([@Mouvedia](https://github.com/Mouvedia)).
-   Fixed: `declaration-property-value-keyword-no-deprecated` autofix of `border-color` and `overflow` ([#8346](https://github.com/stylelint/stylelint/pull/8346)) ([@Mouvedia](https://github.com/Mouvedia)).
-   Fixed: `declaration-property-value-keyword-no-deprecated` false negatives for `overflow-x` and `overflow-y` ([#8340](https://github.com/stylelint/stylelint/pull/8340)) ([@Mouvedia](https://github.com/Mouvedia)).
-   Fixed: `declaration-property-value-keyword-no-deprecated` false negatives for `scrollbar-color` ([#8346](https://github.com/stylelint/stylelint/pull/8346)) ([@Mouvedia](https://github.com/Mouvedia)).
-   Fixed: `declaration-property-value-keyword-no-deprecated` false positives for non-standard syntax values ([#8329](https://github.com/stylelint/stylelint/pull/8329)) ([@Mouvedia](https://github.com/Mouvedia)).
-   Fixed: `declaration-property-value-keyword-no-deprecated` warning message for `overflow: <keyword> <keyword>` ([#8340](https://github.com/stylelint/stylelint/pull/8340)) ([@Mouvedia](https://github.com/Mouvedia)).
-   Fixed: `selector-pseudo-class-no-unknown` false positives for `:has-slotted` ([#8332](https://github.com/stylelint/stylelint/pull/8332)) ([@Mouvedia](https://github.com/Mouvedia)).


## [v16.13.2](https://github.com/stylelint/stylelint/blob/HEAD/CHANGELOG.md#16132---2025-01-14)

It fixes a regression bug with `--fix`.

-   Fixed: `--fix` CLI flag raising unknown value error ([#8313](https://github.com/stylelint/stylelint/pull/8313)) ([@ybiquitous](https://github.com/ybiquitous)).


## [v16.13.1](https://github.com/stylelint/stylelint/blob/HEAD/CHANGELOG.md#16131---2025-01-13)

It fixes one bug due to an upstream change in our `ignore` dependency.

-   Fixed: `ignore.default is not a function` ([#8305](https://github.com/stylelint/stylelint/pull/8305)) ([@romainmenke](https://github.com/romainmenke)).